service: lamdabhai

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  userapi:
    handler: index.handler
    events:
      - http:
          path: /api/users
          method: get
      - http:
          path: /api/messages
          method: get

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
